name: Test

on:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 11.5
        run: sudo xcode-select -s '/Applications/Xcode_11.5.app/Contents/Developer'
      - name: Run test
        run: swift test
