name: Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift_image: 
          - "swift:5.2"
          - "swiftlang/swift:nightly-5.3-bionic"
    container:
      image: ${{ matrix.swift_image }}
    steps:
      - uses: actions/checkout@v2
      - name: Show version
        run: |
          swift --version
      - name: Run test
        run: swift test
  macos:
    name: Test on macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        xcode_version: 
          - "11.5"
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer'
      - name: Show versions
        run: |
          swift --version
          xcodebuild -version
      - name: Run test
        run: swift test
